In [1]:
import pandas as pd
import numpy as np

In [2]:
raw_data = {'regiment': ['Nighthawks', 'Nighthawks', 'Nighthawks', 'Nighthawks', 'Dragoons', 'Dragoons', 'Dragoons', 'Dragoons', 'Scouts', 'Scouts', 'Scouts', 'Scouts'], 
        'company': ['1st', '1st', '2nd', '2nd', '1st', '1st', '2nd', '2nd','1st', '1st', '2nd', '2nd'], 
        'name': ['Miller', 'Jacobson', 'Ali', 'Milner', 'Cooze', 'Jacon', 'Ryaner', 'Sone', 'Sloan', 'Piger', 'Riani', 'Ali'], 
        'preTestScore': [4, 24, 31, 2, 3, 4, 24, 31, 2, 3, 2, 3],
        'postTestScore': [25, 94, 57, 62, 70, 25, 94, 57, 62, 70, 62, 70]}

In [5]:
df = pd.DataFrame(raw_data)

In [6]:
df.head()

     regiment company      name  preTestScore  postTestScore
0  Nighthawks     1st    Miller             4             25
1  Nighthawks     1st  Jacobson            24             94
2  Nighthawks     2nd       Ali            31             57
3  Nighthawks     2nd    Milner             2             62
4    Dragoons     1st     Cooze             3             70

In [7]:
raw_data.keys()

dict_keys(['regiment', 'company', 'name', 'preTestScore', 'postTestScore'])

### Change order of columns

In [9]:
df = pd.DataFrame(raw_data, columns=['name','regiment','company','preTestScore','postTestScore'])

In [10]:
df.head()

       name    regiment company  preTestScore  postTestScore
0    Miller  Nighthawks     1st             4             25
1  Jacobson  Nighthawks     1st            24             94
2       Ali  Nighthawks     2nd            31             57
3    Milner  Nighthawks     2nd             2             62
4     Cooze    Dragoons     1st             3             70

###  What is the mean preTestScore from the regiment Nighthawks?

In [12]:
df[df['regiment'] == 'Nighthawks'].mean(numeric_only=True)

preTestScore     15.25
postTestScore    59.50
dtype: float64

### Present general statistics by company

In [13]:
df.groupby('company').describe()

        preTestScore                                                      \
               count       mean        std  min   25%   50%    75%   max
company
1st              6.0   6.666667   8.524475  2.0  3.00   3.5   4.00  24.0
2nd              6.0  15.500000  14.652645  2.0  2.25  13.5  29.25  31.0

        postTestScore
                count       mean        std   min    25%   50%   75%   max
company
1st               6.0  57.666667  27.485754  25.0  34.25  66.0  70.0  94.0
2nd               6.0  67.000000  14.057027  57.0  58.25  62.0  68.0  94.0

### What is the mean of each company's preTestScore?

In [15]:
df.groupby('company')['preTestScore'].mean()

company
1st     6.666667
2nd    15.500000
Name: preTestScore, dtype: float64

### Present the mean preTestScores grouped by regiment and company

In [16]:
df.groupby(['company', 'regiment'])['preTestScore'].mean()

company  regiment
1st      Dragoons       3.5
         Nighthawks    14.0
         Scouts         2.5
2nd      Dragoons      27.5
         Nighthawks    16.5
         Scouts         2.5
Name: preTestScore, dtype: float64

### Present the mean preTestScores grouped by regiment and company without heirarchical indexing

In [17]:
df.groupby(['company', 'regiment'])['preTestScore'].mean().unstack()

regiment  Dragoons  Nighthawks  Scouts
company
1st            3.5        14.0     2.5
2nd           27.5        16.5     2.5

### Group the entire dataframe by regiment and company

In [19]:
df.groupby(['regiment', 'company']).mean(numeric_only=True)

                    preTestScore  postTestScore
regiment   company
Dragoons   1st               3.5           47.5
           2nd              27.5           75.5
Nighthawks 1st              14.0           59.5
           2nd              16.5           59.5
Scouts     1st               2.5           66.0
           2nd               2.5           66.0

### What is the number of observations in each regiment and company

In [20]:
df.groupby(['regiment', 'company']).size()

regiment    company
Dragoons    1st        2
            2nd        2
Nighthawks  1st        2
            2nd        2
Scouts      1st        2
            2nd        2
dtype: int64

### Iterate over a group and print the name and the whole data from the regiment

In [ ]:
for name, group in regiment.groupby('regiment'):
    # print the name of the regiment
    print(name)
    # print the data of that regiment
    print(group)