In [1]:
import pandas as pd
import numpy as np

###  Create 3 differents Series, each of length 100, as follows:
- The first a random number from 1 to 4
- The second a random number from 1 to 3
- The third a random number from 10,000 to 30,000

In [3]:
s1 = pd.Series(np.random.randint(1, high = 5, size = 100, dtype = np.int32))
s2 = pd.Series(np.random.randint(1, high = 3, size = 100, dtype = np.int32))
s3 = pd.Series(np.random.randint(10000, high = 30000, size = 100, dtype = np.int32))

print(s1, s2, s3)

0     4
1     4
2     4
3     3
4     2
     ..
95    2
96    2
97    4
98    4
99    4
Length: 100, dtype: int32 0     1
1     1
2     2
3     2
4     1
     ..
95    1
96    1
97    1
98    1
99    1
Length: 100, dtype: int32 0     27963
1     15727
2     10535
3     15606
4     19726
      ...
95    15521
96    18581
97    13668
98    23436
99    24636
Length: 100, dtype: int32

### Let's create a DataFrame by joinning the Series by column

In [4]:
dataset = pd.concat([s1, s2, s3], axis =1)
dataset.head()

   0  1      2
0  4  1  27963
1  4  1  15727
2  4  2  10535
3  3  2  15606
4  2  1  19726

### Change the name of the columns to bedrs, bathrs, price_sqr_meter

In [6]:
dataset.rename(columns = {0: ' bedrs', 1: 'bathrs' , 2:'price_sqr_meter'}, inplace=True)
dataset.head()

    bedrs  bathrs  price_sqr_meter
0       4       1            27963
1       4       1            15727
2       4       2            10535
3       3       2            15606
4       2       1            19726

### Create a one column DataFrame with the values of the 3 Series and assign it to 'bigcolumn'

In [7]:
bigcolumn = pd.concat([s1, s2, s3], axis=0)
bigcolumn = bigcolumn.to_frame()
print(type(bigcolumn))
bigcolumn

<class 'pandas.core.frame.DataFrame'>

        0
0       4
1       4
2       4
3       3
4       2
..    ...
95  15521
96  18581
97  13668
98  23436
99  24636

[300 rows x 1 columns]

### it seems it is going only until index 99. Is it true?

In [8]:
len(bigcolumn)

300

### Reindex the DataFrame so it goes from 0 to 299

In [9]:
bigcolumn.reset_index(drop=True, inplace=True)
bigcolumn

         0
0        4
1        4
2        4
3        3
4        2
..     ...
295  15521
296  18581
297  13668
298  23436
299  24636

[300 rows x 1 columns]