## **Loading and Knowing your data**

In [66]:
import pandas as pd
import numpy as np

### Use the 'user_id' as index

In [91]:
url = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user"
df = pd.read_csv(url, sep = '|',index_col ='user_id')

In [95]:
df.head()

         age gender  occupation zip_code
user_id
1         24      M  technician    85711
2         53      F       other    94043
3         23      M      writer    32067
4         24      M  technician    43537
5         33      F       other    15213

In [96]:
df.tail()

         age gender     occupation zip_code
user_id
939       26      F        student    33319
940       32      M  administrator    02215
941       20      M        student    97229
942       48      F      librarian    78209
943       22      M        student    77841

In [97]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 943 entries, 1 to 943
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   age         943 non-null    int64
 1   gender      943 non-null    object
 2   occupation  943 non-null    object
 3   zip_code    943 non-null    object
dtypes: int64(1), object(3)
memory usage: 36.8+ KB

In [99]:
df.shape

(943, 4)

In [101]:
df.columns.to_list()

['age', 'gender', 'occupation', 'zip_code']

### How is the dataset indexed?

In [103]:
df.index

Index([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,
       ...
       934, 935, 936, 937, 938, 939, 940, 941, 942, 943],
      dtype='int64', name='user_id', length=943)

### What is the data type of each column?

In [106]:
df.dtypes

age            int64
gender        object
occupation    object
zip_code      object
dtype: object

### Print only the occupation column

In [107]:
df['occupation']

user_id
1         technician
2              other
3             writer
4         technician
5              other
           ...
939          student
940    administrator
941          student
942        librarian
943          student
Name: occupation, Length: 943, dtype: object

### How many different occupations are in this dataset?

In [108]:
df.occupation.nunique()

21

### What is the most frequent occupation?

In [111]:
df.occupation.value_counts().head()

occupation
student          196
other            105
educator          95
administrator     79
engineer          67
Name: count, dtype: int64

### Summarize the DataFrame.

In [112]:
df.describe()

              age
count  943.000000
mean    34.051962
std     12.192740
min      7.000000
25%     25.000000
50%     31.000000
75%     43.000000
max     73.000000

### Summarize all the columns

In [113]:
df.describe(include = 'all')

               age gender occupation zip_code
count   943.000000    943        943      943
unique         NaN      2         21      795
top            NaN      M    student    55414
freq           NaN    670        196        9
mean     34.051962    NaN        NaN      NaN
std      12.192740    NaN        NaN      NaN
min       7.000000    NaN        NaN      NaN
25%      25.000000    NaN        NaN      NaN
50%      31.000000    NaN        NaN      NaN
75%      43.000000    NaN        NaN      NaN
max      73.000000    NaN        NaN      NaN

### Summarize only the occupation column

In [114]:
df.occupation.describe()

count         943
unique         21
top       student
freq          196
Name: occupation, dtype: object

### What is the mean age of users?

In [115]:
df['age'].mean()

np.float64(34.05196182396607)